# Generated by Django 5.2.4 on 2025-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deal_asking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='risk_explanation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='risk_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='risk_score',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
